use Yao_Li_6210;

--drop all views
drop view if exists Project.StaffPerformanceSummary;
drop view if exists Project.StorePerformanceSummary
drop view if exists Project.CarMakePopularity;

/*
 * This view provides insight into staff performance over the last 30 days by summarizing:
 * 1. Total Number of Car Rentals handled by each staff member, helping identify workload distribution.
 * 2. Total Revenue generated from rentals managed by each staff member, offering insights into individual contributions to the company’s earnings.
 * 3. Orders the data by StoreID and Total Revenue (descending) to highlight top-performing staff within each store. 
 */
create view Project.StaffPerformanceSummary as
select s.StaffID,
s.StoreID,
concat(s.FirstName, ' ', s.LastName) as StaffName,
count(cr.CarRentalID) as TotalRentalsHandled,
sum(cr.TotalAmount) as TotalRevenueGenerated
from Project.Staff s
left join Project.CarRental cr on s.StaffID = cr.StaffID
where cr.RentalStartDate >= dateadd(day, -30, getdate())
group by s.StaffID, s.FirstName, s.LastName, s.StoreID;
--order by 2, 5 desc;


/*
 * This view provides insight into store performance over the last 30 days by summarizing:
 * 1. Total Number of Rentals handled by each store, helping identify the workload distribution.
 * 2. Total Revenue generated by rentals from each store, offering insights into the store’s contribution to company earnings.
 * 3. Orders the data by Total Revenue (descending) to highlight top-performing stores.
 * 
 */
create view Project.StorePerformanceSummary as
select s.StoreID, s.StoreName, 
concat(s.City, ', ', s.State) as Location,
count(cr.CarRentalID) as TotalRentalsHandled, 
sum(cr.TotalAmount) as TotalRevenueGenerated
from Project.Store s
left join Project.CarRental cr on s.StoreID = cr.StoreID
where cr.RentalStartDate >= dateadd(day, -30, getdate())
group by s.StoreID, s.StoreName, s.City, s.State;
--order by 4 desc;
   

/*
 * This view provides insight into the popularity of car makes and their financial performance in the last 30 days by summarizing:
 * 1. Total Number of Rentals for each car make, which helps identify the most frequently rented cars.
 * 2. Total Revenue generated by rentals for each car make, giving an understanding of their contribution to the company’s earnings.
 * 3. Orders the data by the total number of rentals (descending) and total revenue (descending) to highlight the most popular and high-earning car makes.
 */
create view Project.CarMakePopularity as
select c.Make as CarMake,
count(cr.CarRentalID) as TotalRentals,
sum(cr.TotalAmount) as TotalRevenue
from Project.Car c
join Project.CarRental cr on c.CarID = cr.CarID
where cr.RentalStartDate >= dateadd(day, -30, getdate())
group by c.Make;
--order by 2 desc, 3 desc;



select * from Project.StaffPerformanceSummary order by 2, 5 desc;

select * from Project.StorePerformanceSummary order by 4 desc;

select * from Project.CarMakePopularity order by 2 desc, 3 desc;
